---
title: "t Distribution"
output:
  pdf_document: default
  html_document: default
  header-includes:
   - \usepackage{bbm}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, results = 'asis', fig, fig.height = 1.6, fig.width = 4, fig.align = "center"}
library(ggplot2)

library(reshape2)
library(knitr)

library(tinytex)

x<-seq(-4,4,0.1)
ytop<-dnorm(1)
kuwa<-data.frame(x=x,y=dnorm(x))
k<-qplot(x=kuwa$x,y=kuwa$y,geom='line',xlab='T Values', ylab = 'Density')
shade <- rbind(c(1,0), subset(kuwa, x >= 1), c(kuwa[nrow(kuwa), "X"], 0))
k + geom_segment(aes(x=1,y=0,xend=1,yend=ytop)) +
  geom_polygon(data = shade, aes(x, y),alpha=0.3) + theme_classic() + 
  annotate("text", x=1, y=-0.05, label="t[alpha]", parse=TRUE) +
  annotate("text", x=1.54, y=0.05, label="alpha", parse=TRUE) +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank())

tv<-c(.100, .050, .025, .010, .005)

df<-c(1:30,40,60,120,Inf)
a<-qt(1-.1, df)
b<-qt(1-.05, df)
c<-qt(1-.025, df)
d<-qt(1-.010, df)
e<-qt(1-.005, df)
dft<-data.frame(t.100 =a, t.050 =b, t.025 =c, t.010 =d, t.005 =e)

rownames(dft)=c(df[-length(df)], "$\\infty$")

colnames(dft)=c("$t_{.100}$", "$t_{.050}$", "$t_{.025}$", "$t_{.010}$", "$t_{.005}$")

kable(dft)



```
